services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_note_etudiant
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://symfony:2004@db:5432/symfony"
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: 2004
      POSTGRES_DB: symfony
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "symfony", "-U", "symfony"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: